### ISSUE TITLE
<li> must have descendent <p>

### ISSUE THREAD

**Issue by acabal** [davgross/william-wollaston-the-religion-of-nature-delineated#10]
For example in section-5.xhtml, there are several &lt;li&gt;s that have text as a direct descendent.  &lt;li&gt;s should have a &lt;p&gt; tag below them, even if it's just a sentence.  This isn't required by the HTML5 spec, but it helps in consistency when parsing things.

**Comment by davgross** [comment]
Does this apply to the endnotes as well?

**Comment by acabal** [comment]
Yup, though for the endnotes a quick glance suggests there aren't any with more than one paragraph.  So you can probably sort out the endnotes with a regex find and replace.
