### ISSUE TITLE
Many <p> tags have leading/trailing spaces

### ISSUE THREAD

**Issue by acabal** [davgross/william-wollaston-the-religion-of-nature-delineated#11]
See section-5.xhtml for example, almost all &lt;p&gt; tags have leading and trailing space which must be deleted throughout the entire ebook.  This is probably an easy regex.

**Comment by davgross** [comment]
This seems to be added by the "clean" script. If I get rid of them, they just keep coming back.

**Comment by acabal** [comment]
Hmm, I just tried a test on my machine and it worked as expected, that is, it didn't add spaces.  `clean` mostly just uses xmlllint which shouldn't do anything like that to begin with.  Are you running `clean` on a Mac, or an Ubuntu machine?

**Comment by davgross** [comment]
ubuntu

**Comment by acabal** [comment]
OK, must be a weird portability issue.  I'm on Ubuntu 15.04 and `clean` is working as expected.  Can you clean up the <p> spacing anyway, and just don't run a clean, I'll clean it on my end when we're all done.

**Comment by acabal** [comment]
OK, I can't quite figure out why `clean` is adding those spaces.  If you have a moment, would you be interested in inspecting the `clean` script to see at what stage of the process that happens?  Then we could fix the script to ensure portability.

**Comment by davgross** [comment]
Hmmm... I can't replicate the problem. Not sure what happened.
