### ISSUE TITLE
Problems in foreword.xhtml

### ISSUE THREAD

**Issue by acabal** [davgross/william-wollaston-the-religion-of-nature-delineated#14]
- epub:type should be foreword, not prologue
- id should be "foreword", not "section-11"
- I see a dedication in there, that should be split into its own file dedication.xhtml with epub:type "dedication"
- Both should be "frontmatter" not "bodymatter"

**Comment by davgross** [comment]
The dedication and foreword are all of one piece. The foreword takes the form of him explaining to the person who prompted him to write the book that he has done what was asked. It's in the form of a letter to this person, but it's really meant for all readers as a sort of backgrounder.
