### ISSUE TITLE
Halftitle required

### ISSUE THREAD

**Issue by acabal** [davgross/william-wollaston-the-religion-of-nature-delineated#18]
Since there is frontmatter in the book, we must add a half title between the frontmatter and the bodymatter.

See https://github.com/standardebooks/abraham-merritt_the-moon-pool/blob/master/src/epub/text/halftitle.xhtml for an example, you can copy that file entirely.

Make sure to add it to the ToC too, and note that you'll have to add a wrapping `<ol>` tag.  See this ToC for an example: https://github.com/standardebooks/abraham-merritt_the-moon-pool/blob/master/src/epub/toc.xhtml

Note how after the forword, we link to the half title using the book's title in the `<a>` tag; then we open a new `<ol>` to list the chapters.

**Comment by davgross** [comment]
BTW, in the Landmarks section in Moon Pool, "Endnotes" and "Colophon" both link to colophon.xhtml:

```
<a href="text/colophon.xhtml" epub:type="backmatter z3998:fiction rearnotes">Endnotes</a>
<a href="text/colophon.xhtml" epub:type="backmatter colophon">Colophon</a>
```

**Comment by acabal** [comment]
D'oh!  Fixed, thanks :)

(Note that endnotes in Moon Pool are z3998:fiction because they're written by the fictitious narrator)
