### ISSUE TITLE
xml:lang="grc" should be xml:lang="el"

### ISSUE THREAD

**Issue by acabal** [davgross/william-wollaston-the-religion-of-nature-delineated#25]
Found in `endnotes.xhtml` at least.  Make sure to review all xml:lang tags and ensure they're actually IETF language tags.  You can look up the tag for any language at http://r12a.github.io/apps/subtags/

**Comment by davgross** [comment]
Are you sure about this? My understanding was that "el" is modern greek, and "grc" is ancient Greek. Whenever this tag is used, it's to tag ancient Greek text..

**Comment by acabal** [comment]
I see you're right, I learned something today!

In that case this might be an issue to explore in previously produced ebooks, though personally I can't read Greek so I don't know what should be marked as modern vs ancient.  (I imagine some English authors writing in the 1800s and quoting Greek may have massaged the quotes into the modern Greek they were personally familiar with.)
