### ISSUE TITLE
Some sections need titles

### ISSUE THREAD

**Issue by acabal** [davgross/william-wollaston-the-religion-of-nature-delineated#29]
Endnotes, translators-note, foreword, and editors-note all need `<h2 epub:type="title">...</h2>` title as the first child of the `<section>`

Foreword is a bit tricky, because the dedication is also included in that file.  That's another reason to pull the dedication out into its own file, `dedication.xhtml` and place it before the foreword in the spine.  (The dedication doesn't need an `<h2>` title.)  If we do that we can also style it nicely, with centered text and top margins.

**Comment by davgross** [comment]
I don't see how you can pull the dedication and foreword apart. They're conjoined twins, beyond the skills of this surgeon to disjoin.
