### ISSUE TITLE
Improving <ol> styles

### ISSUE THREAD

**Issue by acabal** [davgross/william-wollaston-the-religion-of-nature-delineated#32]
Can you add the following to `local.css`:

```
li > p:first-child,
ol + p{
	text-indent: 0;
}
```

I think this'll improve the look of ordered lists, of which there are a few.  You can check out the foreword for example to see if it looks better with this kind of style.

**Comment by davgross** [comment]
You might want to make this part of the default style if you're going to insist that all <li> elements have <p> elements embedded in them.

**Comment by acabal** [comment]
Yeah... we might get away with altering line 53 in `core.css` to just `p:first-child`.  Let me think about it
